### PR TITLE
Explaining prompts

### PR DESCRIPTION
**Pull request by plijnzaad**
During R workshop in Espoo, a learner got very confused about the '+' prompt (R waiting for more input). Explained it, and how to solve it, and also added bit about how to interact with R.

### CODE REVIEW

**Comment by benmarwick** [comment]
Might also be worth adding that you can also press escape to quit the statement and get the R prompt back, rather than doing trial and error to close the quote/parens

**Comment by plijnzaad** [comment]
thanks, cool, didn't know, will add. Doesn't work for plain R (i.e. outside Rstudio) command console though.

**Comment by benmarwick** [comment]
No worries, Esc in the plain R GUI for windows also breaks out of an incomplete statement (for me), but it's not quite as tidy as in RStudio.

**Comment by tracykteal** [comment]
Thanks @plijnzaad for this addition.

**Pull request merged**
