### PR TITLE
added rna-seq data analysis lesson

### PR DESCRIPTION
**Pull request by stephenturner**
Added two lessons on RNA-seq data analysis. Part I (QC, alignment, & counting) assumes basic familiarity with the Unix shell. Part II (differential expression analysis) assumes basic familiarity with R. I ran this as a [one-day workshop](http://bioconnector.github.io/workshops/lessons/rnaseq-1day/) where in the morning we did an intro to Unix followed by the first lesson here, and in the afternoon we did an introduction to R followed by the second lesson here. More details in the README here, and more about the previous workshop on [this SWC blog post](http://software-carpentry.org/blog/2014/11/virginia-workshop.html). Some lesson material was contributed by @rbeagrie on an outstanding PR to SWC based on a recent Mozilla sprint.

### CODE REVIEW

**Comment by stephenturner** [comment]
I haven't been monitoring the DC mailing list as much as I should have been. Is this repo still being maintained/developed?

**Comment by rbeagrie** [comment]
Actually none of the material was contributed by me - that was the work of @liz-is and @sritchie73. The software carpentry version of the lesson has to be modified to fit the new lesson format (hence the PR is now closed for the moment), which I'm slowly doing over at https://github.com/rbeagrie/capstone-novice-r-bioinfo

**Comment by tracykteal** [comment]
The repo is still being developed and maintained, and I'm so sorry I haven't gotten to your PR. It looks great, and there's just a few comments I have to get through this week.

**Comment by tracykteal** [comment]
I'm so sorry for the slow PR review. These are great lessons! We're going to reorganize our repo, likely with one lesson per repo, but I want to accept this PR to get it in with our lessons. When we sort it out, we'll retain the history. Thanks@stephenturner!

**Pull request merged**
